title: Digital Mudra
email: marcello@tutti.ch

baseurl: "/"

markdown: kramdown

category-list: [services, contact, blog]

plugins:
  - jemoji

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
