title: Digital Mudra
email: marcello@tutti.ch

baseurl: "/digitalmudra"

markdown: kramdown

category-list: [whoami, hack]

plugins:
  - jemoji

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
